openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/portal/api'
info:
  description: 
  version: 1.0.0
  title: Icreated Web Portal
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
    

tags:
  - name: users
    description: Operations about users
  - name: invoices
    description: Operations about invoices
  - name: payments
    description: Operations about payments

paths:
  /invoices:
    get:
      tags:
        - invoices
      summary: Get invoices
      description: Get user invoices
      operationId: getInvoices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  
  /invoices/{id}:
    get:
      tags:
        - invoices
      summary: Get invoice
      description: Get invoice by id
      operationId: getInvoice
      parameters:
        - name: id
          in: path
          description: Invoice id
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  
  /invoices/openitems:
    get:
      tags:
        - invoices
      summary: Get open items
      description: Get open items
      operationId: getOpenItems
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenItem'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

      
components:
  schemas:
    ValueLabel:
      type: object
      properties:
        label:
          type: string
        value:
          type: string    	
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          format: int32
          description: User Status
    Address:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 4
        address1:
          type: string
          description: The first line of the address.
          example: 123 Main Street
        address2:
          type: string
          description: The second line of the address.
          example: Apt 1
        city:
          type: string
          description: The city of the address.
          example: New York
        postal:
          type: string
          description: The zip code of the address.
          example: 10001
        countryName:
          type: string
          description: The country name
    Document: 
      type: object
      description: Order or Invoice for table display
      properties:
        id:
          type: integer
          format: int32
          example: 4
        documentNo:
          type: string
          description: The document number of the order / invoice.
          example: 1000001
        poReference:
          type: string
          description: The PO reference of the order / invoice.
          example: 1000001
        description:
          type: string
          description: The description of the order / invoice.
          example: Invoice for order 1000001
        docStatus:
          type: string
          description: The document status of the order / invoice.
          example: CO
        totalLines:
          type: number
          description: The total lines of the order / invoice.
          format: double
          example: 100.00
        grandTotal:
          type: number
          description: The grand total of the order / invoice.
          format: double
          example: 100.00
        currency:
          type: string
          description: The currency of the order / invoice.
          example: USD
        date:
          type: string
          format: date
          description: The transaction date of the order / invoice.
          example: 2021-01-01
        bpartnerName:
          type: string
          description: The Business Partner of the order / invoice.
          example: John Smith
    Invoice: 
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 4
        documentNo:
          type: string
          description: The document number of the invoice. 
          example: 1000001
        poReference:
          type: string
          description: The PO reference of the invoice.
          example: 1000001
        bpartnerName:
          type: string
          description: The Business Partner of the order / invoice.
          example: John Smith
        description:
          type: string
          description: The description of the invoice.
          example: Invoice for order 1000001
        docStatus:
          type: string
          description: The document status of the invoice.
          example: CO
        totalLines:
          type: number
          description: The total lines of the invoice.
          format: double
          example: 100.00
        grandTotal:
          type: number
          description: The grand total of the invoice.
          format: double
          example: 100.00
        currency:
          type: string
          description: The currency of the invoice.
          example: USD
        date:
          type: string
          format: date
          description: The transaction date of the invoice.
          example: 2021-01-01
        billAddress:
          $ref: '#/components/schemas/Address'
        lines:  
          type: array
          items:
            $ref: '#/components/schemas/InvoiceLine'
        payments:  
          type: array
          items:
            $ref: '#/components/schemas/Payment'
        taxes:  
          type: array
          items:
            $ref: '#/components/schemas/Tax'

    InvoiceLine:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 4
        line:
          type: integer
          format: int64
          description: The line number of the invoice line.
          example: 10
        name:
          type: string
          description: The name of the invoice line.
          example: Product 1
        description:
          type: string
          description: The description of the invoice line.
          example: Invoice line for order 1000001
        qty:
          type: number
          description: The quantity of the invoice line.
          format: double
          example: 1.00
        price:
          type: number
          description: The price of the invoice line.
          format: double
          example: 100.00
        priceList:
          type: number
          description: The price list of the invoice line.
          format: double
          example: 100.00
        lineNetAmt:
          type: number
          description: The line net amount of the invoice line.
          format: double
          example: 100.00

    Payment:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 4
        documentNo:
          type: string
          description: The document number of the payment.
          example: 1000001
        description:
          type: string
          description: The description of the payment.
          example: Payment for order 1000001
        docStatus:
          type: string
          description: The document status of the payment.
          example: CO
        payAmt:
          type: number
          description: The amount of the payment.
          format: double
          example: 100.00
        trxid:
          type: string
          description: The transaction ID of the payment.
          example: 1000001
        currency:
          type: string
          description: The currency of the payment.
          example: USD
        tenderType:
          type: string
          description: The tender type of the payment.
          example: C
        date:
          type: string
          format: date
          description: The transaction date of the payment.
          example: 2021-01-01

    Tax:
      type: object
      properties: 
        name:
          type: string
          description: The name of the tax.
          example: State Tax
        tax:
          type: number
          description: The tax rate.
          format: double
          example: 0.05 

    OpenItem:
        type: object
        properties:
          invoiceId:
            type: integer
            format: int32
            example: 4
          orderId:
            type: integer
            format: int32
            example: 4
          bpartnerId:
            type: integer
            format: int32
            example: 4
          bpartnerLocationId:
            type: integer
            format: int32
            example: 4
          currencyId:
            type: integer
            format: int32
            example: 4
          documentNo:
            type: string
            description: The document number of the invoice.
            example: 1000001
          description:
            type: string
            description: The description of the invoice.
            example: Invoice for order 1000001
          docStatus:
            type: string
            description: The document status of the invoice.
            example: CO
          isSOTRX:
            type: boolean
            description: The transaction type is sale or purchase.
            example: true
          isActive:
            type: boolean
            description: The invoice is active.
            example: true
          dateOrdered:
            type: string
            format: date
            description: The order date of the invoice.
            example: 2021-01-01
          dateInvoiced: 
            type: string
            format: date
            description: The invoice date of the invoice.
            example: 2021-01-01
          dueDate: 
            type: string
            format: date
            description: The due date of the invoice.
            example: 2021-01-01
          netDays:
            type: integer
            format: int32
            example: 20
          totalLines:
            type: number
            description: The total lines of the invoice.
            format: double
            example: 100.00
          grandTotal: 
            type: number
            description: The grand total of the invoice.
            format: double
            example: 100.00
          openAmt:  
            type: number
            description: The open amount of the invoice.
            format: double
            example: 100.00
          paidAmt:
            type: number
            description: The paid amount of the invoice.
            format: double
            example: 100.00